### ISSUE TITLE
Productionize CORS

### ISSUE THREAD

**Issue by cailyncodes** [ctoec/winged-keys#13]
i imagine in prod we may not actually want to AllowAll for CORs. worth adding a comment here so we come back to this pre-prod

_Originally posted by @jlhogan in https://github.com/_render_node/MDI0OlB1bGxSZXF1ZXN0UmV2aWV3Q29tbWVudDM0Njg0NDc1MQ==/comments/review_comment_

**Comment by JordanGuinn** [comment]
Closed with https://github.com/ctoec/winged-keys/pull/36.
