### ISSUE TITLE
Environment - Beanstalk - ability to run in AWS Beanstalk environment

### ISSUE THREAD

**Issue by speedcm** [ctoec/winged-keys#7]
As an member of the OPS team I would like to be able to deploy winged-keys to AWS Beanstalk.

In order to run under AWS Beanstalk, the winged-keys application (i.e. IdentifyServer) needs to provide a run-time configuration that is AWS Beanstalk compliant.

It appears that others have solved this issue by:

- Setting RequireSsl to false in the source code
- Setting PublicOrigin in the source code

For more information on possible fix, see IdentityServer/IdentityServer3#1820

**Comment by cailyncodes** [comment]
@speedcm Can we close this issue?
