### ISSUE TITLE
Deployment - Ability to execute on non-developer desktop

### ISSUE THREAD

**Issue by speedcm** [ctoec/winged-keys#8]
As a member of the OPS team, I need the ability to deploy winged-keys to a UAT environment. 

Winged keys is currently hardwired to execute only on  a developer desktop.  The application must use application properties (e.g. appsettings.json) to allow it to execute on  AWS system.

Example:  options.IssuerUri = https://winged-keys:5050

**Comment by cailyncodes** [comment]
This should be resolved by #11
